const $=id=>document.getElementById(id);
let products=JSON.parse(localStorage.getItem("fazenda_estoque_produtos")||"[]");
let movements=JSON.parse(localStorage.getItem("fazenda_estoque_movimentos")||"[]");
function save(){localStorage.setItem("fazenda_estoque_produtos",JSON.stringify(products));localStorage.setItem("fazenda_estoque_movimentos",JSON.stringify(movements));if(window.AdminFazendaSync){window.AdminFazendaSync("fazenda_estoque_produtos",products);window.AdminFazendaSync("fazenda_estoque_movimentos",movements)}}
function esc(t){const d=document.createElement("div");d.textContent=t??"";return d.innerHTML}
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function today(){let d=new Date(),o=d.getTimezoneOffset();return new Date(d-o*60000).toISOString().slice(0,10)}
function dateBR(v){return v?new Date(v+"T00:00:00").toLocaleDateString("pt-BR"):"-"}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.tab-content").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
function refreshSelect(){let current=$("movementProduct").value;$("movementProduct").innerHTML='<option value="">Selecione um produto</option>'+products.map(p=>`<option value="${p.id}">${esc(p.name)} (${p.quantity.toLocaleString("pt-BR")} ${esc(p.unit)})</option>`).join("");$("movementProduct").value=current}
function stats(){let n=new Date(),m=n.getMonth(),y=n.getFullYear(),en=0,ex=0;movements.forEach(x=>{let d=new Date(x.date+"T00:00:00");if(d.getMonth()===m&&d.getFullYear()===y){if(x.type==="Entrada")en+=x.quantity;else ex+=x.quantity}});$("productCount").textContent=products.length;$("monthEntries").textContent=en.toLocaleString("pt-BR");$("monthExits").textContent=ex.toLocaleString("pt-BR");$("lowStock").textContent=products.filter(p=>p.quantity<=p.minimum).length}
function renderProducts(){let q=$("productSearch").value.toLowerCase(),c=$("categoryFilter").value,list=products.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!c||p.category===c));$("productTable").innerHTML=list.length?list.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.category)}</td><td><strong>${p.quantity.toLocaleString("pt-BR")} ${esc(p.unit)}</strong></td><td>${p.minimum.toLocaleString("pt-BR")} ${esc(p.unit)}</td><td>${money(p.value)}</td><td><span class="badge ${p.quantity<=p.minimum?"low":"ok"}">${p.quantity<=p.minimum?"Estoque baixo":"Normal"}</span></td><td><button class="action-btn" onclick="editProduct('${p.id}')">✏️</button><button class="action-btn" onclick="deleteProduct('${p.id}')">🗑️</button></td></tr>`).join(""):'<tr class="empty-row"><td colspan="7"><div>📦</div><strong>Nenhum produto cadastrado</strong><span>Clique em Novo produto para começar.</span></td></tr>'}
function renderHistory(){let q=$("historySearch").value.toLowerCase(),t=$("typeFilter").value,list=movements.filter(x=>(!q||x.productName.toLowerCase().includes(q))&&(!t||x.type===t));$("historyTable").innerHTML=list.length?list.map(x=>`<tr><td>${dateBR(x.date)}</td><td><strong>${esc(x.productName)}</strong></td><td><span class="badge ${x.type}">${x.type}</span></td><td>${x.quantity.toLocaleString("pt-BR")} ${esc(x.unit)}</td><td>${esc(x.reason)}</td><td>${esc(x.reference)||"-"}</td><td>${x.source?`<span title="Movimentação automática">🔗</span>`:`<button class="action-btn" onclick="deleteMovement(\'${x.id}\')">🗑️</button>`}</td></tr>`).join(""):'<tr class="empty-row"><td colspan="7"><div>📋</div><strong>Nenhuma movimentação</strong><span>As entradas e saídas aparecerão aqui.</span></td></tr>'}
function refresh(){renderProducts();renderHistory();refreshSelect();stats()}
$("newProduct").onclick=()=>{$("productForm").reset();$("productId").value="";$("productFormTitle").textContent="Cadastrar produto";$("productFormBox").classList.remove("hidden")};
$("cancelProduct").onclick=()=>$("productFormBox").classList.add("hidden");
$("productForm").onsubmit=e=>{e.preventDefault();let id=$("productId").value,name=$("stockName").value.trim(),qty=Number($("initialQuantity").value||0);if(id){let p=products.find(x=>x.id===id);p.name=name;p.category=$("stockCategory").value;p.unit=$("stockUnit").value;p.minimum=Number($("minimumStock").value||0);p.value=Number($("unitValue").value||0);p.notes=$("productNotes").value.trim()}else{let p={id:Date.now().toString(),name,category:$("stockCategory").value,unit:$("stockUnit").value,quantity:qty,minimum:Number($("minimumStock").value||0),value:Number($("unitValue").value||0),notes:$("productNotes").value.trim()};products.unshift(p);if(qty>0)movements.unshift({id:"m"+Date.now(),date:today(),type:"Entrada",productId:p.id,productName:p.name,quantity:qty,unit:p.unit,reason:"Estoque inicial",reference:"Cadastro",notes:""})}save();$("productFormBox").classList.add("hidden");refresh();alert("Produto salvo com sucesso!")};
window.editProduct=id=>{let p=products.find(x=>x.id===id);if(!p)return;$("productId").value=p.id;$("stockName").value=p.name;$("stockCategory").value=p.category;$("stockUnit").value=p.unit;$("initialQuantity").value=p.quantity;$("initialQuantity").disabled=true;$("minimumStock").value=p.minimum;$("unitValue").value=p.value;$("productNotes").value=p.notes;$("productFormTitle").textContent="Alterar produto";$("productFormBox").classList.remove("hidden");$("productFormBox").scrollIntoView({behavior:"smooth"});setTimeout(()=>$("initialQuantity").disabled=false,500)};
window.deleteProduct=id=>{let p=products.find(x=>x.id===id);if(!p||!confirm(`Excluir "${p.name}" do estoque?`))return;products=products.filter(x=>x.id!==id);save();refresh()};
$("movementForm").onsubmit=e=>{e.preventDefault();let p=products.find(x=>x.id===$("movementProduct").value),qty=Number($("movementQuantity").value),type=$("movementType").value;if(!p)return alert("Selecione um produto.");if(type==="Saída"&&qty>p.quantity)return alert(`Estoque insuficiente. Disponível: ${p.quantity.toLocaleString("pt-BR")} ${p.unit}.`);p.quantity+=type==="Entrada"?qty:-qty;movements.unshift({id:"m"+Date.now(),date:$("movementDate").value,type,productId:p.id,productName:p.name,quantity:qty,unit:p.unit,reason:$("movementReason").value,reference:$("movementReference").value.trim(),notes:$("movementNotes").value.trim()});save();e.target.reset();$("movementDate").value=today();refresh();alert("Movimentação registrada com sucesso!")};
window.deleteMovement=id=>{let x=movements.find(m=>m.id===id);if(!x||!confirm("Excluir esta movimentação e corrigir o saldo do estoque?"))return;let p=products.find(a=>a.id===x.productId);if(p){if(x.type==="Entrada"){if(p.quantity<x.quantity)return alert("Não é possível excluir esta entrada porque o saldo atual ficaria negativo.");p.quantity-=x.quantity}else p.quantity+=x.quantity}movements=movements.filter(m=>m.id!==id);save();refresh()};
["productSearch","historySearch"].forEach(id=>$(id).addEventListener("input",refresh));["categoryFilter","typeFilter"].forEach(id=>$(id).addEventListener("change",refresh));$("movementDate").value=today();refresh();