const $=id=>document.getElementById(id);
let cattle=JSON.parse(localStorage.getItem("fazenda_gado")||"[]");
const get=k=>JSON.parse(localStorage.getItem(k)||"[]"),put=(k,v)=>{localStorage.setItem(k,JSON.stringify(v));return window.AdminFazendaSync?window.AdminFazendaSync(k,v):Promise.resolve()};
function esc(t){const d=document.createElement("div");d.textContent=t??"";return d.innerHTML}
function dateBR(v){return v?new Date(v+"T00:00:00").toLocaleDateString("pt-BR"):"-"} function today(){const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)}
const lotCategories=new Set(["Peixes","Ovos"]);
const femaleCategories=new Set(["Vaca","Bezerra","Égua","Pata","Galinha","Galinha-d'Angola"]);
const maleCategories=new Set(["Boi","Touro","Bezerro","Cavalo","Pato","Galo"]);
function qty(a){return lotCategories.has(a.category)?Math.max(0,Number(a.quantity||0)):1}
function stats(){const active=cattle.filter(a=>a.status==="Ativo");$("totalCattle").textContent=active.filter(a=>a.category!=="Ovos").reduce((n,a)=>n+qty(a),0);$("totalCows").textContent=active.filter(a=>a.category==="Vaca").length;$("totalBirds").textContent=active.filter(a=>["Pato","Pata","Galinha","Galo","Galinha-d'Angola"].includes(a.category)).length;$("totalOther").textContent=active.filter(a=>["Cavalo","Égua","Peixes","Ovos"].includes(a.category)).reduce((n,a)=>n+qty(a),0)}
function render(){const q=$("searchAnimal").value.toLowerCase().trim(),cat=$("categoryFilter").value,st=$("statusFilter").value;const list=cattle.filter(a=>(!q||String(a.tag||"").toLowerCase().includes(q)||String(a.name||"").toLowerCase().includes(q)||String(a.breed||"").toLowerCase().includes(q))&&(!cat||a.category===cat)&&(!st||a.status===st));$("cattleTable").innerHTML=list.length?list.map(a=>`<tr><td><strong>#${esc(a.tag)}</strong></td><td><strong>${esc(a.name)||"Sem nome"}</strong><br><small>${esc(a.sex||"-")}</small></td><td><span class="category-badge">${esc(a.category)}</span>${a.category==="Vaca"?`<br><small>${a.isCalved?"Parida ":""}${a.isDairy?"Leiteira":""}</small>`:""}</td><td>${lotCategories.has(a.category)?qty(a).toLocaleString("pt-BR")+" un":esc(a.breed)||"-"}</td><td>${dateBR(a.birthDate)}</td><td>${a.weight?Number(a.weight).toLocaleString("pt-BR")+" kg":"-"}</td><td><span class="badge ${a.status}">${esc(a.status)}</span></td><td><button class="action-btn" title="Alterar" onclick="editAnimal('${a.id}')">✏️</button><button class="action-btn" title="Excluir" onclick="deleteAnimal('${a.id}')">🗑️</button></td></tr>`).join(""):'<tr class="empty-row"><td colspan="8"><div>🐄</div><strong>Nenhum cadastro encontrado</strong><span>Cadastre um animal, lote de peixes ou ovos.</span></td></tr>'}
function toggleCategory(){const c=$("category").value;$("cowDetails").classList.toggle("hidden",c!=="Vaca");$("quantityField").classList.toggle("hidden",!lotCategories.has(c));$("individualFieldsNote").classList.toggle("hidden",!lotCategories.has(c));if(femaleCategories.has(c))$("sex").value="Fêmea";if(maleCategories.has(c))$("sex").value="Macho";if(c==="Ovos")$("sex").value="-"}
function toggleFinance(){let buy=$("origin").value==="Compra",sold=$("status").value==="Vendido";$("purchaseValueField").classList.toggle("hidden",!buy);$("purchaseSupplierField").classList.toggle("hidden",!buy);$("saleDateField").classList.toggle("hidden",!sold);$("saleValueField").classList.toggle("hidden",!sold);$("saleBuyerField").classList.toggle("hidden",!sold)}
function syncFinance(a){let expenses=get("fazenda_despesas"),sales=get("fazenda_vendas");expenses=expenses.filter(x=>!(x.source==="gado"&&x.sourceId===a.id));sales=sales.filter(x=>!(x.source==="gado"&&x.sourceId===a.id));if(a.origin==="Compra"&&a.purchaseValue>0)expenses.unshift({id:"gado-compra-"+a.id,date:a.entryDate||today(),item:`Compra ${a.category} #${a.tag}${a.name?" - "+a.name:""}`,category:"Outros",supplier:a.purchaseSupplier||"",quantity:1,unit:"un",unitValue:a.purchaseValue,total:a.purchaseValue,payment:"Outro",status:"Pago",reference:`Animais #${a.tag}`,receiptName:"",notes:"Lançamento automático gerado pelo módulo Animais.",source:"gado",sourceId:a.id});if(a.status==="Vendido"&&a.saleValue>0)sales.unshift({id:"gado-venda-"+a.id,date:a.saleDate||today(),customer:a.saleBuyer||"Comprador não informado",product:`${a.category} #${a.tag}${a.name?" - "+a.name:""}`,quantity:1,unit:"un",unitPrice:a.saleValue,total:a.saleValue,paymentMethod:"Outro",paymentStatus:"Pago",receiptName:"",notes:"Lançamento automático gerado pelo módulo Animais.",source:"gado",sourceId:a.id});put("fazenda_despesas",expenses);put("fazenda_vendas",sales)}
function removeFinance(id){put("fazenda_despesas",get("fazenda_despesas").filter(x=>!(x.source==="gado"&&x.sourceId===id)));put("fazenda_vendas",get("fazenda_vendas").filter(x=>!(x.source==="gado"&&x.sourceId===id)))}
function resetForm(){const f=$("cattleForm");f.reset();$("animalId").value="";$("formTitle").textContent="Cadastrar animal / lote";$("saveButton").textContent="💾 Salvar cadastro";$("cancelEdit").classList.add("hidden");$("entryDate").value=today();$("saleDate").value=today();toggleCategory();toggleFinance()}
$("category").addEventListener("change",toggleCategory);$("origin").addEventListener("change",toggleFinance);$("status").addEventListener("change",toggleFinance);
$("cattleForm").addEventListener("submit",async e=>{e.preventDefault();const id=$("animalId").value,tag=$("tag").value.trim();if(cattle.some(a=>String(a.tag).toLowerCase()===tag.toLowerCase()&&a.id!==id))return alert("Já existe um cadastro com essa identificação.");let buy=$("origin").value==="Compra",sold=$("status").value==="Vendido",pv=Number($("purchaseValue").value||0),sv=Number($("saleValue").value||0);if(buy&&pv<=0)return alert("Informe o valor da compra.");if(sold&&sv<=0)return alert("Informe o valor da venda.");if(sold&&!$("saleBuyer").value.trim())return alert("Informe o comprador.");const category=$("category").value;const obj={id:id||Date.now().toString(),tag,name:$("animalName").value.trim(),category,sex:$("sex").value,breed:$("breed").value.trim(),birthDate:$("birthDate").value,weight:Number($("weight").value||0),mother:$("mother").value.trim(),father:$("father").value.trim(),entryDate:$("entryDate").value,origin:$("origin").value,status:$("status").value,quantity:lotCategories.has(category)?Math.max(1,Number($("quantity").value||1)):1,isCalved:category==="Vaca"&&$("isCalved").checked,isDairy:category==="Vaca"&&$("isDairy").checked,purchaseValue:pv,purchaseSupplier:$("purchaseSupplier").value.trim(),saleDate:$("saleDate").value,saleValue:sv,saleBuyer:$("saleBuyer").value.trim(),notes:$("notes").value.trim()};const before=JSON.parse(JSON.stringify(cattle));const btn=$("saveButton");btn.disabled=true;btn.textContent="Salvando no Firebase...";try{if(!window.AdminFazendaSaveItem)throw new Error("Conexão Firebase não inicializada");await window.AdminFazendaSaveItem("fazenda_gado",obj);if(id){const i=cattle.findIndex(a=>a.id===id);cattle[i]=obj}else cattle.unshift(obj);localStorage.setItem("fazenda_gado",JSON.stringify(cattle));syncFinance(obj);resetForm();render();stats();alert("Cadastro salvo no Firebase com sucesso!")}catch(err){console.error("Erro ao salvar",err);cattle=before;localStorage.setItem("fazenda_gado",JSON.stringify(cattle));render();stats();alert("ERRO: o cadastro NÃO foi salvo no Firebase. "+(err?.message||"Verifique a conexão."))}finally{btn.disabled=false;if(!$("animalId").value)btn.textContent="💾 Salvar cadastro"}});
window.editAnimal=id=>{const a=cattle.find(x=>x.id===id);if(!a)return;$("animalId").value=a.id;$("tag").value=a.tag;$("animalName").value=a.name;$("category").value=a.category;$("sex").value=a.sex||"Fêmea";$("breed").value=a.breed||"";$("birthDate").value=a.birthDate||"";$("weight").value=a.weight||"";$("mother").value=a.mother||"";$("father").value=a.father||"";$("entryDate").value=a.entryDate||today();$("origin").value=a.origin||"Nascido na fazenda";$("status").value=a.status||"Ativo";$("quantity").value=a.quantity||1;$("isCalved").checked=!!a.isCalved;$("isDairy").checked=!!a.isDairy;$("purchaseValue").value=a.purchaseValue||"";$("purchaseSupplier").value=a.purchaseSupplier||"";$("saleDate").value=a.saleDate||today();$("saleValue").value=a.saleValue||"";$("saleBuyer").value=a.saleBuyer||"";$("notes").value=a.notes||"";$("formTitle").textContent="Alterar cadastro";$("saveButton").textContent="💾 Salvar alteração";$("cancelEdit").classList.remove("hidden");toggleCategory();toggleFinance();window.scrollTo({top:0,behavior:"smooth"})};
window.deleteAnimal=async id=>{const a=cattle.find(x=>x.id===id);if(!a||!confirm(`Excluir #${a.tag}${a.name?" - "+a.name:""}?`))return;try{if(!window.AdminFazendaDeleteItem)throw new Error("Conexão Firebase não inicializada");await window.AdminFazendaDeleteItem("fazenda_gado",id);cattle=cattle.filter(x=>x.id!==id);localStorage.setItem("fazenda_gado",JSON.stringify(cattle));removeFinance(id);render();stats();alert("Cadastro excluído do Firebase com sucesso.")}catch(e){console.error(e);alert("ERRO: não foi possível excluir no Firebase. "+(e?.message||"Verifique a conexão."))}};
$("cancelEdit").onclick=resetForm;$("cattleForm").addEventListener("reset",()=>setTimeout(()=>{if(!$("animalId").value){$("entryDate").value=today();$("saleDate").value=today();toggleCategory();toggleFinance()}},0));$("searchAnimal").addEventListener("input",render);["categoryFilter","statusFilter"].forEach(id=>$(id).addEventListener("change",render));$("entryDate").value=today();$("saleDate").value=today();toggleCategory();toggleFinance();render();stats();
