const form=document.getElementById("productionForm"),dateInput=document.getElementById("productionDate"),table=document.getElementById("productionTable"),search=document.getElementById("searchProduction"),productSelect=document.getElementById("product"),unitSelect=document.getElementById("unit");
let productions=JSON.parse(localStorage.getItem("fazenda_producao")||"[]");
const getStock=()=>JSON.parse(localStorage.getItem("fazenda_estoque_produtos")||"[]"),getMoves=()=>JSON.parse(localStorage.getItem("fazenda_estoque_movimentos")||"[]");
const saveStock=(p,m)=>{localStorage.setItem("fazenda_estoque_produtos",JSON.stringify(p));localStorage.setItem("fazenda_estoque_movimentos",JSON.stringify(m));if(window.AdminFazendaSync){window.AdminFazendaSync("fazenda_estoque_produtos",p);window.AdminFazendaSync("fazenda_estoque_movimentos",m)}};
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})} function today(){const d=new Date(),o=d.getTimezoneOffset();return new Date(d-o*60000).toISOString().slice(0,10)} function dateBR(v){return v?new Date(v+"T00:00:00").toLocaleDateString("pt-BR"):"-"} function esc(t){const d=document.createElement("div");d.textContent=t??"";return d.innerHTML}
function loadProducts(){let ps=getStock(),cur=productSelect.value;productSelect.innerHTML='<option value="">Selecione um produto do estoque</option>'+ps.map(p=>`<option value="${p.id}">${esc(p.name)} — ${p.quantity.toLocaleString("pt-BR")} ${esc(p.unit)}</option>`).join("");productSelect.value=cur}
productSelect.onchange=()=>{let p=getStock().find(x=>x.id===productSelect.value);if(p){[...unitSelect.options].some(o=>{if(o.text.toLowerCase()===p.unit.toLowerCase()||o.value.toLowerCase()===p.unit.toLowerCase()){unitSelect.value=o.value;return true}})}};
function updateStats(){const now=new Date(),m=now.getMonth(),y=now.getFullYear();let qty=0,cost=0;productions.forEach(p=>{const d=new Date(p.date+"T00:00:00");if(d.getMonth()===m&&d.getFullYear()===y){qty+=p.quantity;cost+=p.cost}});document.getElementById("recordCount").textContent=productions.length;document.getElementById("monthQuantity").textContent=qty.toLocaleString("pt-BR");document.getElementById("monthCost").textContent=money(cost);document.getElementById("lastProduction").textContent=productions.length?dateBR(productions[0].date):"-"}
function render(){const q=search.value.toLowerCase().trim(),list=productions.filter(p=>!q||p.product.toLowerCase().includes(q)||p.batch.toLowerCase().includes(q));table.innerHTML=list.length?list.map(p=>`<tr><td>${dateBR(p.date)}</td><td><strong>${esc(p.product)}</strong></td><td>${p.quantity.toLocaleString("pt-BR")}</td><td>${esc(p.unit)}</td><td>${money(p.cost)}</td><td>${esc(p.batch)||"-"}</td><td><button class="action-btn" onclick="deleteProduction('${p.id}')">🗑️</button></td></tr>`).join(""):`<tr class="empty-row"><td colspan="7"><div>🏭</div><strong>Nenhuma produção encontrada</strong><span>Cadastre uma produção ou altere a pesquisa.</span></td></tr>`}
form.onsubmit=e=>{e.preventDefault();let products=getStock(),movements=getMoves(),sp=products.find(x=>x.id===productSelect.value);if(!sp)return alert("Cadastre ou selecione primeiro um produto no Estoque.");let qty=Number(document.getElementById("quantity").value);if(qty<=0)return alert("Informe uma quantidade válida.");let id=Date.now().toString(),p={id,date:dateInput.value,productId:sp.id,product:sp.name,quantity:qty,unit:sp.unit,cost:Number(document.getElementById("cost").value||0),batch:document.getElementById("batch").value.trim(),notes:document.getElementById("notes").value.trim()};sp.quantity+=qty;movements.unshift({id:"prod-"+id,date:p.date,type:"Entrada",productId:sp.id,productName:sp.name,quantity:qty,unit:sp.unit,reason:"Produção",reference:"Produção #"+id,source:"producao",sourceId:id,notes:p.notes});productions.unshift(p);localStorage.setItem("fazenda_producao",JSON.stringify(productions));if(window.AdminFazendaSync)window.AdminFazendaSync("fazenda_producao",productions);saveStock(products,movements);form.reset();dateInput.value=today();loadProducts();render();updateStats();alert("Produção cadastrada e adicionada ao estoque com sucesso!")};
window.deleteProduction=id=>{let p=productions.find(x=>x.id===id);if(!p||!confirm(`Excluir a produção de ${p.product} e retirar essa entrada do estoque?`))return;let products=getStock(),movements=getMoves(),sp=products.find(x=>x.id===p.productId),mv=movements.find(x=>x.source==="producao"&&x.sourceId===id);let qty=mv?mv.quantity:p.quantity;if(sp&&sp.quantity<qty)return alert(`Não é possível excluir: o estoque atual de ${sp.name} é ${sp.quantity.toLocaleString("pt-BR")} ${sp.unit}, menor que a entrada desta produção.`);if(sp)sp.quantity-=qty;movements=movements.filter(x=>!(x.source==="producao"&&x.sourceId===id));productions=productions.filter(x=>x.id!==id);localStorage.setItem("fazenda_producao",JSON.stringify(productions));if(window.AdminFazendaSync)window.AdminFazendaSync("fazenda_producao",productions);saveStock(products,movements);loadProducts();render();updateStats()};
search.oninput=render;dateInput.value=today();loadProducts();render();updateStats();