const form=document.getElementById("serviceForm"),dateEl=document.getElementById("serviceDate"),timeEl=document.getElementById("serviceTime"),table=document.getElementById("serviceTable"),search=document.getElementById("searchService"),filter=document.getElementById("statusFilter"),editId=document.getElementById("editingId"),cancel=document.getElementById("cancelEdit"),title=document.getElementById("formTitle"),save=document.getElementById("saveButton");
let services=JSON.parse(localStorage.getItem("fazenda_servicos")||"[]");
const $=id=>document.getElementById(id);
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function today(){const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)}
function dateBR(v){return v?new Date(v+"T00:00:00").toLocaleDateString("pt-BR"):"-"}
function esc(t){const d=document.createElement("div");d.textContent=t??"";return d.innerHTML}
function persist(){localStorage.setItem("fazenda_servicos",JSON.stringify(services));if(window.AdminFazendaSync)window.AdminFazendaSync("fazenda_servicos",services)}
function stats(){const n=new Date(),m=n.getMonth(),y=n.getFullYear();let mc=0,mv=0,p=0;services.forEach(s=>{const d=new Date(s.date+"T00:00:00");if(d.getMonth()===m&&d.getFullYear()===y){mc++;mv+=s.value}if(s.status!=="Pago")p+=s.value});$("serviceCount").textContent=services.length;$("monthCount").textContent=mc;$("monthValue").textContent=money(mv);$("pendingValue").textContent=money(p)}
function render(){const q=search.value.toLowerCase().trim(),st=filter.value;const list=services.filter(s=>(!q||s.name.toLowerCase().includes(q)||s.responsible.toLowerCase().includes(q))&&(!st||s.status===st));if(!list.length){table.innerHTML='<tr class="empty-row"><td colspan="8"><div>🔧</div><strong>Nenhum serviço encontrado</strong><span>Cadastre um serviço ou altere os filtros.</span></td></tr>';return}table.innerHTML=list.map(s=>`<tr><td>${dateBR(s.date)}<br><small>${esc(s.time)}</small></td><td><strong>${esc(s.name)}</strong><br><small>${esc(s.category)}</small></td><td><span class="direction ${s.direction}">${s.direction}</span></td><td>${esc(s.responsible)}</td><td><strong>${money(s.value)}</strong></td><td>${esc(s.payment)}</td><td><span class="badge ${s.status}">${s.status}</span></td><td><button class="action-btn" title="Alterar" onclick="editService('${s.id}')">✏️</button><button class="action-btn" title="Excluir" onclick="deleteService('${s.id}')">🗑️</button></td></tr>`).join("")}
function resetEdit(){editId.value="";title.textContent="Adicionar serviço";save.textContent="💾 Salvar serviço";cancel.classList.add("hidden");form.reset();dateEl.value=today();timeEl.value=new Date().toTimeString().slice(0,5)}
form.addEventListener("submit",e=>{e.preventDefault();const obj={id:editId.value||Date.now().toString(),date:dateEl.value,time:timeEl.value,direction:$("serviceDirection").value,name:$("serviceName").value.trim(),responsible:$("responsible").value.trim(),value:Number($("serviceValue").value),payment:$("paymentMethod").value,status:$("paymentStatus").value,category:$("category").value,notes:$("notes").value.trim()};if(editId.value){const i=services.findIndex(s=>s.id===editId.value);services[i]=obj}else services.unshift(obj);persist();resetEdit();render();stats();alert("Serviço salvo com sucesso!")});
window.editService=id=>{const s=services.find(x=>x.id===id);if(!s)return;editId.value=s.id;dateEl.value=s.date;timeEl.value=s.time;$("serviceDirection").value=s.direction;$("serviceName").value=s.name;$("responsible").value=s.responsible;$("serviceValue").value=s.value;$("paymentMethod").value=s.payment;$("paymentStatus").value=s.status;$("category").value=s.category;$("notes").value=s.notes;title.textContent="Alterar serviço";save.textContent="💾 Salvar alteração";cancel.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})};
window.deleteService=id=>{const s=services.find(x=>x.id===id);if(!s||!confirm(`Excluir o serviço "${s.name}"?`))return;services=services.filter(x=>x.id!==id);persist();render();stats()};
cancel.addEventListener("click",resetEdit);form.addEventListener("reset",()=>setTimeout(()=>{if(!editId.value){dateEl.value=today();timeEl.value=new Date().toTimeString().slice(0,5)}},0));search.addEventListener("input",render);filter.addEventListener("change",render);dateEl.value=today();timeEl.value=new Date().toTimeString().slice(0,5);render();stats();
